defaults:
  - petsc_ksp_default
# _target_: nigbms.modules.solvers.PETScKSP
params_fix:
  # ksp
  ksp_type: cg
  ksp_divtol: 1.0e+10
  ksp_norm_type: unpreconditioned
  # pc
  pc_type: none
debug: False